EcommerceBundle\Entity\AdresseClient:
    type: entity
    table: null
    repositoryClass: EcommerceBundle\Repository\AdresseClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        AdresseModele:
            targetEntity: EcommerceBundle\Entity\AdresseModele
    lifecycleCallbacks: {  }
