EcommerceBundle\Entity\AdresseModele:
    type: entity
    table: null
    repositoryClass: EcommerceBundle\Repository\AdresseModeleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adrTypeName:
            type: string
            length: '50'
            column: adr_type_name
        adrNom:
            type: string
            length: '50'
            column: adr_nom
        adrPrenom:
            type: string
            length: '50'
            column: adr_prenom
        adrSoc:
            type: string
            length: '100'
            nullable: true
            column: adr_soc
        adrEmail:
            type: string
            length: '100'
            nullable: true
            column: adr_email
        adrTel:
            type: string
            length: '20'
            nullable: true
            column: adr_tel
        adrAdr:
            type: string
            length: '100'
            column: adr_adr
        adrCp:
            type: string
            length: '20'
            column: adr_cp
        adrVille:
            type: string
            length: '50'
            column: adr_ville
        adrPays:
            type: string
            length: '50'
            nullable: true
            column: adr_pays
    manyToOne:
        adrIdcom:
            targetEntity: EcommerceBundle\Entity\Commande
            joinColumn:
                name: adr_idcom
                referencedColumnName: id
    oneToMany:
        AdresseModele:
            targetEntity: EcommerceBundle\Entity\AdresseModele
            mappedBy: AdresseModele
            cascade: [persist]

    lifecycleCallbacks: {  }
