EcommerceBundle\Entity\Prodlib:
    type: entity
    table: null
    repositoryClass: EcommerceBundle\Repository\ProdlibRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pdlLocale:
            type: string
            length: '2'
            column: pdl_locale
        pdlLib:
            type: string
            length: '100'
            nullable: true
            column: pdl_lib
        pdlDesc:
            type: text
            nullable: true
            column: pdl_desc
        pdlCat:
            type: string
            length: '50'
            nullable: true
            column: pdl_cat
        pdlType:
            type: string
            length: '50'
            nullable: true
            column: pdl_type
        pdlItem:
            type: string
            length: '50'
            nullable: true
            column: pdl_item
        pdlInfoLib1:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib1
        pdlInfoLib2:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib2
        pdlInfoLib3:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib3
        pdlInfoLib4:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib4
        pdlInfoLib5:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib5
        pdlInfoLib6:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib6
        pdlInfoLib7:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib7
        pdlInfoLib8:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib8
        pdlInfoLib9:
            type: string
            length: '50'
            nullable: true
            column: pdl_info_lib9
        pdlInfoVal1:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val1
        pdlInfoVal2:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val2
        pdlInfoVal3:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val3
        pdlInfoVal4:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val4
        pdlInfoVal5:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val5
        pdlInfoVal6:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val6
        pdlInfoVal7:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val7
        pdlInfoVal8:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val8
        pdlInfoVal9:
            type: string
            length: '100'
            nullable: true
            column: pdl_info_val9
        pdlPckgComm:
            type: string
            length: 255
            nullable: true
            column: pdl_pckg_comm
        pdlDispo:
            type: string
            length: '100'
            nullable: true
            column: pdl_dispo
        pdlFabDelai:
            type: string
            length: '100'
            nullable: true
            column: pdl_fab_delai
        pdlLivDelai:
            type: string
            length: '100'
            nullable: true
            column: pdl_liv_delai
    manyToOne:
        pdlIdpdt:
            targetEntity: EcommerceBundle\Entity\Produit
            joinColumn:
                name: pdl_idpdt
                referencedColumnName: id
    lifecycleCallbacks: {  }
