EcommerceBundle\Entity\Produit:
    type: entity
    table: null
    repositoryClass: EcommerceBundle\Repository\ProduitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pdtEtat:
            type: boolean
            column: pdt_etat
        pdtAvendre:
            type: boolean
            nullable: true
            column: pdt_avendre
        pdtAffNostock:
            type: boolean
            nullable: true
            column: pdt_aff_nostock
        pdtAffPrix:
            type: boolean
            nullable: true
            column: pdt_aff_prix
        pdtNom:
            type: string
            length: '50'
            unique: true
            column: pdt_nom
        pdtRef:
            type: string
            length: '30'
            unique: true
            column: pdt_ref
        pdtPrixUnitHt:
            type: decimal
            precision: '9'
            scale: '2'
            column: pdt_prix_unit_ht
        pdtPrixUnitTtc:
            type: decimal
            precision: '9'
            scale: '2'
            column: pdt_prix_unit_ttc
        pdtPromoPct:
            type: smallint
            nullable: true
            column: pdt_promo_pct
        pdtPromoHt:
            type: decimal
            precision: '9'
            scale: '2'
            nullable: true
            column: pdt_promo_ht
        pdtPromoTtc:
            type: decimal
            precision: '9'
            scale: '2'
            nullable: true
            column: pdt_promo_ttc
        pdtPhoto:
            type: string
            length: '50'
            column: pdt_photo
        pdtPhoto2:
            type: string
            length: '50'
            nullable: true
            column: pdt_photo2
        pdtPhoto3:
            type: string
            length: '50'
            nullable: true
            column: pdt_photo3
        pdtPhoto4:
            type: string
            length: '50'
            nullable: true
            column: pdt_photo4
        pdtPhoto5:
            type: string
            length: '50'
            nullable: true
            column: pdt_photo5
        pdtInfoVal1:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val1
        pdtInfoVal2:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val2
        pdtInfoVal3:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val3
        pdtInfoVal4:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val4
        pdtInfoVal5:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val5
        pdtInfoVal6:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val6
        pdtInfoVal7:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val7
        pdtInfoVal8:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val8
        pdtInfoVal9:
            type: string
            length: '100'
            nullable: true
            column: pdt_info_val9
        pdtPoids:
            type: string
            length: '50'
            nullable: true
            column: pdt_poids
        pdtDim:
            type: string
            length: '50'
            nullable: true
            column: pdt_dim
        pdtEmbPoids:
            type: string
            length: '50'
            nullable: true
            column: pdt_emb_poids
        pdtEmbDim:
            type: string
            length: '50'
            nullable: true
            column: pdt_emb_dim
        pdtPckgPhoto:
            type: string
            length: '30'
            nullable: true
            column: pdt_pckg_photo
    manyToOne:
      pdtIdtva:
        targetEntity: EcommerceBundle\Entity\Tva
        joinColumn:
          name: pdt_idtva
          referencedColumnName: id
    lifecycleCallbacks: {  }
