abontnews_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:Abontnews:index" }
    methods:  GET

abontnews_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:Abontnews:show" }
    methods:  GET

abontnews_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:Abontnews:new" }
    methods:  [GET, POST]

abontnews_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:Abontnews:edit" }
    methods:  [GET, POST]

abontnews_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:Abontnews:delete" }
    methods:  [GET, DELETE]
