adresse_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:Adresse:index" }
    methods:  GET

adresse_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:Adresse:edit" }
    methods:  [GET, POST]

adresse_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:Adresse:delete" }
    methods:  DELETE
