catlib_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:Catlib:index" }
    methods:  GET

catlib_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:Catlib:show" }
    methods:  GET

catlib_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:Catlib:new" }
    methods:  [GET, POST]

catlib_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:Catlib:edit" }
    methods:  [GET, POST]

catlib_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:Catlib:delete" }
    methods:  DELETE
