appun:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /eco

app:
    resource: "@AppBundle/Controller/"
    type:     annotation