bague:
    resource: "@BagueBundle/Resources/config/routing.yml"
    prefix:   /site

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
