images_index:
    path:     /
    defaults: { _controller: "AppBundle:Image:index" }
    methods:  GET

images_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Image:show" }
    methods:  GET

images_new:
    path:     /new
    defaults: { _controller: "AppBundle:Image:new" }
    methods:  [GET, POST]

images_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Image:edit" }
    methods:  [GET, POST]

images_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Image:delete" }
    methods:  [GET, DELETE]
