download_nwl:
    path:     /{id}/download
    defaults: { _controller: EcommerceBundle:Newsletter:download }
    methods:  GET

destinataires_nwl:
    path:     /{id}/recupDestinataires
    defaults: { _controller: EcommerceBundle:Newsletter:recupDestinataires }
    methods:  GET

envoi_nwl:
    path:     /{id}/envoiNewsletter
    defaults: { _controller: EcommerceBundle:Newsletter:envoiNewsletter }
    methods:  GET

ecommerce_lang:
    resource: "@EcommerceBundle/Resources/config/routing/lang.yml"
    prefix:   /admin/lng

ecommerce_tva:
    resource: "@EcommerceBundle/Resources/config/routing/tva.yml"
    prefix:   /admin/tva

ecommerce_abontnews:
    resource: "@EcommerceBundle/Resources/config/routing/abontnews.yml"
    prefix:   /admin/abontnews

ecommerce_newsletter:
    resource: "@EcommerceBundle/Resources/config/routing/newsletter.yml"
    prefix:   /admin/newsletter

ecommerce_param:
    resource: "@EcommerceBundle/Resources/config/routing/param.yml"
    prefix:   /admin/param

ecommerce_paramlib:
    resource: "@EcommerceBundle/Resources/config/routing/paramlib.yml"
    prefix:   /admin/paramlib

ecommerce_categorie:
    resource: "@EcommerceBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

ecommerce_catlib:
    resource: "@EcommerceBundle/Resources/config/routing/catlib.yml"
    prefix:   /admin/catlib

ecommerce_produit:
    resource: "@EcommerceBundle/Resources/config/routing/produit.yml"
    prefix:   /admin/produit

ecommerce_prodlib:
    resource: "@EcommerceBundle/Resources/config/routing/prodlib.yml"
    prefix:   /admin/prodlib

ecommerce_commande:
    resource: "@EcommerceBundle/Resources/config/routing/commande.yml"
    prefix:   /admin/commande

ecommerce_adresse:
    resource: "@EcommerceBundle/Resources/config/routing/adresse.yml"
    prefix:   /admin/adresse

ecommerce_adresse_show:
    path:     /adresse/show
    defaults: { _controller: "EcommerceBundle:Adresse:show" }
    methods:  GET

ecommerce_adresse_new:
    path:     /adresse/new
    defaults: { _controller: "EcommerceBundle:Adresse:new" }
    methods:  [GET, POST]

ecommerce_adresse_edit:
    path:     /adresse/edit
    defaults: { _controller: "EcommerceBundle:Adresse:editsession" }
    methods:  [GET, POST]

ecommerce_admin:
    path:     /admin
    defaults: { _controller: EcommerceBundle:Admin:index }

ecommerce_tableau:
    path:     /tableaux
    defaults: { _controller: EcommerceBundle:Tableau:index }

ecommerce_triTableaux:
    path:     /{id}/tritableaux
    defaults: { _controller: EcommerceBundle:Tableau:triTableaux }
    methods:  GET

ecommerce_bijou:
    path:     /bijoux
    defaults: { _controller: EcommerceBundle:Bijou:index }

ecommerce_triBijoux:
    path:     /{id}/tribijoux
    defaults: { _controller: EcommerceBundle:Bijou:triBijoux }
    methods:  GET

ecommerce_detail_produit:
    path:     /{id}/produit
    defaults: { _controller: EcommerceBundle:Detailproduit:index }

ecommerce_panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:index }

ecommerce_add_panier:
    path:     /{id}/addpanier
    defaults: { _controller: EcommerceBundle:Panier:addPanier }
    methods:  GET

ecommerce_remove_panier:
    path:     /{id}/removepanier
    defaults: { _controller: EcommerceBundle:Panier:removePanier }
    methods:  GET
