services:
#    ecommerce.example:
#        class: EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
#
#        arguments => @doctrine  ==>  Pour permettre l'accès aux données de la bdd

    abont.newsletters:
        class: EcommerceBundle\Abonnement\Abonnement
        arguments: [@doctrine.orm.entity_manager]

    recup.langues:
        class: EcommerceBundle\Langues\Langues
        arguments: [@doctrine.orm.entity_manager]

    download.pdf:
        class: EcommerceBundle\Downloads\Pdf

