services:
#    ecommerce.example:
#        class: EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    recup.langues:
        class: EcommerceBundle\Langues\Langues
        arguments: [@doctrine.orm.entity_manager]
