# EcommerceBundle/Resources/config/validation.yml
EcommerceBundle\Entity\Lang:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: lngCode
            message: "Code langue déjà existant"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: lngLib
            message: "Code lib déjà existant"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: lngFlag
            message: "Code flag déjà existant"
    properties:
        file:
            - Image: ~
#    properties:
#        lngCode:
#            - Choice:
#                choices:  [fr, en, de, it, es, pt, el, ja, zh, ko, ru]
#                message:  "Sélectionnez un code valide"

#EcommerceBundle\Entity\Lang:
#    properties:
#        city: [New York, Berlin, Tokyo]
#        gender:
#            - Choice:
#                choices:  [male, female]
#                message:  Choose a valid gender.
#

EcommerceBundle\Entity\Categorie:
    properties:
        phCateg:
            - Image: ~

EcommerceBundle\Entity\Paramlib:
    properties:
        phProdts:
            - Image: ~
        phPanier:
            - Image: ~

EcommerceBundle\Entity\Produit:
    properties:
        phProdt:
            - Image: ~
        phPackag:
            - Image: ~
#        phProdt2:
#            - Image: ~

EcommerceBundle\Entity\Catlib:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [ctlIdcat, ctlLocale]
            errorPath: ctlLocale
            message:  "Langue déjà gérée pour cette catégorie"

EcommerceBundle\Entity\Abontnews:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: anlEmail
            message: "Adresse mail déjà existante"
    properties:
        anlEmail:
            - Email: ~
