app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Homepage:index }

app_kifa:
    path:     /kifa
    defaults: { _controller: AppBundle:Default:index }

app_lucieactu:
    path:     /lucieetactualites
    defaults: { _controller: AppBundle:Actualite:index }

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:index}