bague_index:
    path:     /
    defaults: { _controller: "BagueBundle:Bague:index" }
    methods:  GET

bague_show:
    path:     /{id}/show
    defaults: { _controller: "BagueBundle:Bague:show" }
    methods:  GET

bague_new:
    path:     /new
    defaults: { _controller: "BagueBundle:Bague:new" }
    methods:  [GET, POST]

bague_edit:
    path:     /{id}/edit
    defaults: { _controller: "BagueBundle:Bague:edit" }
    methods:  [GET, POST]

bague_delete:
    path:     /{id}/delete
    defaults: { _controller: "BagueBundle:Bague:delete" }
    methods:  DELETE
